### ISSUE TITLE
Team2_Proposal_Feedback by KanuKim97, BBongDDa

### ISSUE THREAD

**Issue by KanuKim97** [Team-Perseus/Projects_Description#10]
# 기획서
>  ## 아이디어 우수성 및 타당성
> - 문맥 간의 개연성이 부족합니다 이런 문맥을 사용하는 경우는 프로그램 스펙시트에 사용하는 것이니  개연성을 고려하여 작성해 주시기 바랍니다.
>
> ##  실현 가능성
>  - 기존 앱과 기타 앱을 비교하였다면 우리 어플리케이션은 어떻게 이것을 고치고 구현 및 실현하는 것 인지를 말하는 항목입니다.
>  - 해당 애플리케이션의 실현 가능성을 팀의 객관적인 시선에서 판단하는 것입니다.
>  - 구현 리스트를 적지 마시고 객관적인 시선에서 이것이 어떻게 실현되어야 하는 것인지 잘 생각해 보시기 바랍니다.
>   예시) 오픈 API의 객체 구성이 JSON으로 되어있어 이를 활용에 용이한 데이터로 변경해야합니다. ~~~~
>         
> ##  개인 역량
>   - 어떤 프로젝트를 했는지 Github 링크를 걸어두면 조금 더 역량 파악이 쉽습니다.
>   - 학부 수준의 활용 가능하다는 것이 무엇을 의미하는지 알기 어렵습니다.

# 설계도
>  - 지적 사항 없습니다. 깔끔하게 잘 완성하셨습니다.
 
# 일정
> -  추가적인 일정에 대한 역할 분담과 대략적인 기간을 산정해 주시기 바랍니다.  

# 기타 질문 사항
>  - 다른 추가적인 뷰 없이 메인 화면 하나로만 구동되는 것인지 알고 싶습니다.
>   Reply 부탁 드립니다.

**Comment by KanuKim97** [comment]
다른 추가적인 뷰 없이 메인 화면 하나로만 구동되는 것인지 알고 싶습니다.
Reply 부탁 드립니다

**Comment by rkdmfqka** [comment]
> 다른 추가적인 뷰 없이 메인 화면 하나로만 구동되는 것인지 알고 싶습니다.
> Reply 부탁 드립니다

응급처치방법은 별도의 링크, 그림을 통해 볼 수 있도록 표현해야 하기 때문에 하나로만 구동된다고 보기에는 어렵습니다. 그러나 view가 추가되어도 1~2개 정도로 한정될 것으로 예상됩니다.
