### ISSUE TITLE
Team1_Proposal_Feedback by KanuKim97, BBongDDa

### ISSUE THREAD

**Issue by KanuKim97** [Team-Perseus/Projects_Description#11]
# 기획서
> ## 아이디어 우수성 및 타당성   
> - '이번 프로젝트에서 제작할 웹 사이트는 학습용에 가까워 수익을 크게 고려하지는 않았지만'  쓸모 없는 문단입니다 제거해주세요
> -  해당되는 서비스가 미리 존재하는지 또한 해당 서비스가 있다면 문제점이 무엇인지 해당 서비스가 없는지 에 대한 시장 조사 항목이 존재하지 않습니다. 
> -  '게시자는 자신이 코디한 이미지를 업로드함으로써 패션을 뽐냄과 동시에 다른 이용 간의 소통의 공간을 마련한다.'
>  ->해당 내용은 이미 존재하는 sns서비스와 다를게 없어 보입니다.,
>  
> ## 실현가능성
> -  해당 애플리케이션의 실현 가능성을 팀의 객관적인 시선에서 판단하는 것입니다.
> -  구현리스트를 적지 마시고 객관적인 시선에서 이것이 어떻게 실현되어야 하는 것인지 > 잘 생각해 보시기 바랍니다.

# 설계
> -  DFD로 구성을 잘 하셨습니다.
> -  하지만 아래 웹페이지의 UI/UX 구성간 (배너)가 무엇을 의미하는 것인지 알고 싶습니다.
> - UI/UX 구성간 Figma, Lunacy, Adobe XD를 사용하시면 더욱 깔끔한 페이지가 완성될 것입니다.
   
# 일정
> - 일정에 대한 큰 틀을 분류하신 것과 담당자 선정 커밋 예정일을 지정하여 표시해 두셨습니다.
> -  하지만 담당자의 개발 기간의 가독성이 매우 떨어지니 보색으로 처리해 주시기 바랍니다.

**Comment by KanuKim97** [comment]
'게시자는 자신이 코디한 이미지를 업로드함으로써 패션을 뽐냄과 동시에 다른 이용 간의 소통의 공간을 마련한다.'
->해당 내용은 이미 존재하는 sns서비스와 다를게 없어 보입니다.
본인들의 의견을 reply 해주기 바랍니다.

**Comment by suhyeon07** [comment]
> '게시자는 자신이 코디한 이미지를 업로드함으로써 패션을 뽐냄과 동시에 다른 이용 간의 소통의 공간을 마련한다.'
> ->해당 내용은 이미 존재하는 sns서비스와 다를게 없어 보입니다.
> 본인들의 의견을 reply 해주기 바랍니다.

1. <마이스타일>은 개인의 포괄적인 일상을 공유하는 sns와 달리 '패션'이란 주제를 가진다는 점에서 차별성을 보입니다. 
2. 이미지와 코멘트만을 공유하는 sns와 달리 <마이스타일>은 코디에 이용한 아이템의 칸을 분리함으로써 게시자로 하여금 상품의 정보(링크)를 조회자에게 전달할 것을 권장합니다. 게시자는 이와 동시에 자신의 코디와 아이템에 대한 선호도를 각각 구분하여 확인할 수 있습니다. 
3. 인기 게시글 페이지를 통해 게시자가 자신의 코디가 어느정도의 대중성을 갖는지에 대해 파악하고 만족감을 느낄 수 있도록 한다는 점에서 sns와 분리됩니다.
