### ISSUE TITLE
Team3_ Proposal_Feedback by KanuKim97

### ISSUE THREAD

**Issue by KanuKim97** [Team-Perseus/Projects_Description#2]
# 기획서
> ## 아이디어 우수성 및 타당성
> - '기존 어플이 있지만 아직 많지 않을 뿐더러 몇몇 기능이 없어 불편해하는 사용자들
   피드백을 볼 수 있었다.' 라는 구문에 '어떤 피드백이 있었고 기존 어플리케이션에서 
  어떤 기능이 우리 어플리케이션에 추가되어 편할 것이다' 라는 식의 힘을 실어주는 
  구문이 필요해 보입니다.
>  - 디자인 등을 개선한다고 했는데 어떤 점에서 기존의 어플과 어떤 차별성을 보이는지
    기술하는 항목이 있다면 더 좋을 것 같습니다. 
>
> ## 실현 가능성
> - 구현 리스트를 적어놨습니다.
> - 기존 항목을 삭제 후 어플에 들어가야 할 것.pdf 부분이 
    실현 가능성 부분에 들어가서 자연스럽게 연결하는 것이 더 좋아보입니다.
> - 공공 데이터 포털 오픈 API의 어떤 API인지 세부적인 내용을 적어주는 것도 좋습니다.
> - 기존 길 찾기 어플 API를 카카오 네비게이션 API로 수정 부탁드립니다.
> - 디자인 -> 안드로이드 스튜디오(Java||Kotlin)이 아니라 
>   구현 -> 안드로이드 스튜디오(Java||Kotlin)이 맞는 말 같습니다.
>
> ## 개인 역량
> - 어떤 프로젝트를 했는지 기술한 것은 좋았으나 프로젝트의 github주소가 있다면
>  내가 어떤 프로젝트를 했는지 증명하기 더 쉽습니다.

# 설계도
> - UI/UX설계도 입니다.
> - 프로그램 내부의 전반적인 설계를 짜는 것이 설계도 입니다.
   따라서 해당 설계도를 프로그램 내부 처리 로직의 전반적인 설계를 보여줄 수 있는
   Flow Chart로 새로 수정해주시기 바랍니다.
   자세한 항목은 아래의 URL을 첨부하시면 될 것 같습니다.

# 일정
> - 전반적으로 깔끔하나 앱 기능 구현 파트에서 '메인'이라는 부분이 메인 기능인지 
    어플리케이션의 메인페이지 인지 중의성을 띄는 것 같습니다.  

# 기타 질문사항
> - 데이터 베이스의 사용 여부가 포함되어 있지 않습니다.
    데이터 베이스를 사용하지 않는지 reply해주시면 좋겠습니다.

## URL (Flow Chart와 Data Flow Diagram)
>[https://ko.wikipedia.org/wiki/%EC%88%9C%EC%84%9C%EB%8F%84](url)
>[https://ko.wikipedia.org/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%9D%90%EB%A6%84%EB%8F%84](url)

**Comment by KanuKim97** [comment]
기타 질문사항에 대하여 답변해주세요~

**Comment by princesssuna** [comment]
데이터베이스 사용합니다...

**Comment by KanuKim97** [comment]
> 데이터베이스 사용합니다...

답변 감사합니다 남은 기간동안 피드백 사항을 토대로 열심히 수정하세용~

**Comment by KanuKim97** [comment]
# Team3 Feedback
>  - 설계도 v4에 대한 항목을 별 말 하지 않겠습니다. 하지만 나중을 고려한다면 figma나 Xd를 사용하시는 것을 추천 드립니다.
>  - Flow chart 우측 하단의 큰 원이 무슨 기능을 의미하는지 상세하게 기술해줬으면 합니다.   
> - 추가적으로 즐겨 찾기 기능에서만 로그인이 사용되는 것으로 보이는데
> - 해당 로그인 기능이 특정 기능을 block한다면 오히려 사용자의 편의성 측면에서 큰 불편을 가져올 수도 있는데 로그인 기능이 필요한 이유를 reply해주시면 감사하겠습니다.

    팬데믹에 따른 단기 영향에도 불구하고 향후 10년 동안 지속적으로 성장할 것으로 예상된다. 
    전기차 보급 증가에 따른 충전 인프라의 필요성이 인식되어 전기차 충전소 또한 증가하고 있다는 점에서
    아이디어가 우수하다고 생각한다. 
    그러나 전기차 충전소는 일반 주유소에 비해 개수가 적기 때문에 이를 알려주는 어플이 필요하다. 
     -> 아이디어가 우수하다 하지만 전기 차 충전소가 부족하다? 

    => 코로나 팬데믹에 따른 단기 영향에도 불구하고 향후 10년동안 지속적으로 성장할 것으로 예상됩니다.
        따라서 향후 10년 동안의 전기차의 보급증가에 따른 충전 인프라의 필요성이 인식되고 
        정부의 친환경 정책에 따른 전기차 충전소의 설치가 증가하는 추세입니다.
        그러나 전기차 충전소는 아직 일반 주유소에 비해 충전소의 개수가 적기 때문에 이를 사용자에게 알려주는 어플이 필요하다고 생각합니다.
        기존 어플들이 존재하지만 아직은 많지 않을뿐 ~~~

**Comment by KanuKim97** [comment]
해당 로그인 기능이 특정 기능을 block한다면 오히려 사용자의 편의성 측면에서 큰 불편을 가져올 수도 있는데 로그인 기능이 필요한 이유를 reply해주시면 감사하겠습니다.

**Comment by sc0116** [comment]
로그인기능을 추가한 이유는 즐겨찾기기능을 사용하기 위해서 입니다. 로컬에 저장하는 방법을 듣고 검색을 해봤으나 잘모르는 방법이라 어떻게 검색해봐야 될지 모르겠습니다.

**Comment by KanuKim97** [comment]
> 로그인기능을 추가한 이유는 즐겨찾기기능을 사용하기 위해서 입니다. 로컬에 저장하는 방법을 듣고 검색을 해봤으나 잘모르는 방법이라 어떻게 검색해봐야 될지 모르겠습니다. 

다시 말해서 해결방안은 아직 잘 모른다는 거네요?

**Comment by sc0116** [comment]
네 그렇습니다. 원래 로컬 저장에 대한 지식이 없었기 때문에 로컬로 저장할 생각도 못했습니다. 새벽에 알게된 내용이라 급하게 찾는중입니다.
